<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\Customer;
use App\Models\BDM;
use Carbon\Carbon;

class ProjectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get first available customer and BDM
        $customer = Customer::first();
        $bdm = BDM::first();

        if (!$customer || !$bdm) {
            $this->command->warn('Please create at least one customer and one BDM/employee first.');
            return;
        }

        $projects = [
            [
                'customer_id' => $customer->id,
                'customer_name' => $customer->name,
                'customer_mobile' => $customer->mobile ?? '9876543210',
                'customer_email' => $customer->email,
                'project_name' => 'E-Commerce Website - Fashion Store',
                'project_type' => 'Website',
                'start_date' => Carbon::now()->subDays(60),
                'project_valuation' => 150000.00,
                'upfront_payment' => 50000.00,
                'first_installment' => 50000.00,
                'second_installment' => 50000.00,
                'third_installment' => 0.00,
                'upfront_paid' => true,
                'upfront_paid_date' => Carbon::now()->subDays(60),
                'first_installment_paid' => true,
                'first_installment_paid_date' => Carbon::now()->subDays(30),
                'second_installment_paid' => false,
                'third_installment_paid' => false,
                'project_coordinator' => $bdm->name,
                'project_coordinator_id' => $bdm->user_id ?? $bdm->id,
                'bdm_id' => $bdm->id,
                'status' => 'In Progress',
                'project_status' => 'In Progress',
                'current_installment' => 2,
                'domain_name' => 'fashionstore.com',
                'domain_purchase_date' => Carbon::now()->subDays(65),
                'domain_amount' => 1200.00,
                'domain_renewal_cycle' => 'Yearly',
                'domain_renewal_date' => Carbon::now()->addDays(300),
                'hosting_provider' => 'AWS',
                'hosting_purchase_date' => Carbon::now()->subDays(65),
                'hosting_amount' => 5000.00,
                'hosting_renewal_cycle' => 'Yearly',
                'hosting_renewal_date' => Carbon::now()->addDays(300),
                'maintenance_enabled' => true,
                'maintenance_type' => 'Chargeable',
                'maintenance_months' => 12,
                'maintenance_charge' => 3000.00,
                'maintenance_billing_cycle' => 'Monthly',
                'maintenance_start_date' => Carbon::now()->addDays(5),
                'notes' => 'E-commerce platform with payment gateway integration, inventory management, and admin panel.',
            ],
            [
                'customer_id' => $customer->id,
                'customer_name' => $customer->name,
                'customer_mobile' => $customer->mobile ?? '9876543210',
                'customer_email' => $customer->email,
                'project_name' => 'School Management Software',
                'project_type' => 'Software',
                'start_date' => Carbon::now()->subDays(90),
                'project_valuation' => 250000.00,
                'upfront_payment' => 100000.00,
                'first_installment' => 75000.00,
                'second_installment' => 75000.00,
                'third_installment' => 0.00,
                'upfront_paid' => true,
                'upfront_paid_date' => Carbon::now()->subDays(90),
                'first_installment_paid' => true,
                'first_installment_paid_date' => Carbon::now()->subDays(45),
                'second_installment_paid' => true,
                'second_installment_paid_date' => Carbon::now()->subDays(10),
                'third_installment_paid' => false,
                'project_coordinator' => $bdm->name,
                'project_coordinator_id' => $bdm->user_id ?? $bdm->id,
                'bdm_id' => $bdm->id,
                'status' => 'Completed',
                'project_status' => 'Completed',
                'current_installment' => 3,
                'domain_name' => 'schoolmanagement.com',
                'domain_purchase_date' => Carbon::now()->subDays(95),
                'domain_amount' => 1500.00,
                'domain_renewal_cycle' => 'Yearly',
                'domain_renewal_date' => Carbon::now()->addDays(270),
                'hosting_provider' => 'Digital Ocean',
                'hosting_purchase_date' => Carbon::now()->subDays(95),
                'hosting_amount' => 8000.00,
                'hosting_renewal_cycle' => 'Yearly',
                'hosting_renewal_date' => Carbon::now()->addDays(270),
                'maintenance_enabled' => true,
                'maintenance_type' => 'Chargeable',
                'maintenance_months' => 24,
                'maintenance_charge' => 5000.00,
                'maintenance_billing_cycle' => 'Monthly',
                'maintenance_start_date' => Carbon::now()->subDays(5),
                'notes' => 'Complete school management system with student, teacher, fee management modules.',
            ],
            [
                'customer_id' => $customer->id,
                'customer_name' => $customer->name,
                'customer_mobile' => $customer->mobile ?? '9876543210',
                'customer_email' => $customer->email,
                'project_name' => 'Mobile App - Food Delivery',
                'project_type' => 'Application',
                'start_date' => Carbon::now()->subDays(30),
                'project_valuation' => 350000.00,
                'upfront_payment' => 150000.00,
                'first_installment' => 100000.00,
                'second_installment' => 100000.00,
                'third_installment' => 0.00,
                'upfront_paid' => true,
                'upfront_paid_date' => Carbon::now()->subDays(30),
                'first_installment_paid' => false,
                'second_installment_paid' => false,
                'third_installment_paid' => false,
                'project_coordinator' => $bdm->name,
                'project_coordinator_id' => $bdm->user_id ?? $bdm->id,
                'bdm_id' => $bdm->id,
                'status' => 'In Progress',
                'project_status' => 'In Progress',
                'current_installment' => 1,
                'domain_name' => 'fooddeliveryapp.com',
                'domain_purchase_date' => Carbon::now()->subDays(35),
                'domain_amount' => 2000.00,
                'domain_renewal_cycle' => 'Yearly',
                'domain_renewal_date' => Carbon::now()->addDays(330),
                'hosting_provider' => 'Google Cloud',
                'hosting_purchase_date' => Carbon::now()->subDays(35),
                'hosting_amount' => 12000.00,
                'hosting_renewal_cycle' => 'Yearly',
                'hosting_renewal_date' => Carbon::now()->addDays(330),
                'maintenance_enabled' => true,
                'maintenance_type' => 'Chargeable',
                'maintenance_months' => 12,
                'maintenance_charge' => 15000.00,
                'maintenance_billing_cycle' => 'Quarterly',
                'maintenance_start_date' => Carbon::now()->addDays(15),
                'notes' => 'Android & iOS app for food delivery with restaurant panel and delivery tracking.',
            ],
            [
                'customer_id' => $customer->id,
                'customer_name' => $customer->name,
                'customer_mobile' => $customer->mobile ?? '9876543210',
                'customer_email' => $customer->email,
                'project_name' => 'Corporate Website - IT Company',
                'project_type' => 'Website',
                'start_date' => Carbon::now()->subDays(15),
                'project_valuation' => 75000.00,
                'upfront_payment' => 40000.00,
                'first_installment' => 35000.00,
                'second_installment' => 0.00,
                'third_installment' => 0.00,
                'upfront_paid' => true,
                'upfront_paid_date' => Carbon::now()->subDays(15),
                'first_installment_paid' => false,
                'second_installment_paid' => false,
                'third_installment_paid' => false,
                'project_coordinator' => $bdm->name,
                'project_coordinator_id' => $bdm->user_id ?? $bdm->id,
                'bdm_id' => $bdm->id,
                'status' => 'In Progress',
                'project_status' => 'In Progress',
                'current_installment' => 1,
                'domain_name' => 'itcompany.com',
                'domain_purchase_date' => Carbon::now()->subDays(20),
                'domain_amount' => 1000.00,
                'domain_renewal_cycle' => 'Yearly',
                'domain_renewal_date' => Carbon::now()->addDays(345),
                'hosting_provider' => 'Hostinger',
                'hosting_purchase_date' => Carbon::now()->subDays(20),
                'hosting_amount' => 3000.00,
                'hosting_renewal_cycle' => 'Yearly',
                'hosting_renewal_date' => Carbon::now()->addDays(345),
                'maintenance_enabled' => false,
                'notes' => 'Simple corporate website with about, services, portfolio and contact pages.',
            ],
            [
                'customer_id' => $customer->id,
                'customer_name' => $customer->name,
                'customer_mobile' => $customer->mobile ?? '9876543210',
                'customer_email' => $customer->email,
                'project_name' => 'Inventory Management System',
                'project_type' => 'Software',
                'start_date' => Carbon::now()->subDays(120),
                'project_valuation' => 200000.00,
                'upfront_payment' => 80000.00,
                'first_installment' => 60000.00,
                'second_installment' => 60000.00,
                'third_installment' => 0.00,
                'upfront_paid' => true,
                'upfront_paid_date' => Carbon::now()->subDays(120),
                'first_installment_paid' => true,
                'first_installment_paid_date' => Carbon::now()->subDays(60),
                'second_installment_paid' => true,
                'second_installment_paid_date' => Carbon::now()->subDays(20),
                'third_installment_paid' => false,
                'project_coordinator' => $bdm->name,
                'project_coordinator_id' => $bdm->user_id ?? $bdm->id,
                'bdm_id' => $bdm->id,
                'status' => 'Completed',
                'project_status' => 'Completed',
                'current_installment' => 3,
                'maintenance_enabled' => true,
                'maintenance_type' => 'Chargeable',
                'maintenance_months' => 12,
                'maintenance_charge' => 4000.00,
                'maintenance_billing_cycle' => 'Monthly',
                'maintenance_start_date' => Carbon::now()->subDays(15),
                'notes' => 'Desktop software for inventory tracking, stock management and reporting.',
            ],
        ];

        foreach ($projects as $projectData) {
            Project::create($projectData);
        }

        $this->command->info('5 sample projects created successfully!');
    }
}
